### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Jera1dl** [burkejasonj/Mystic-SMP#1]
No matter if I'm in a cave or above ground, my minimap is stuck being black.  I can still see player heads, but no map details.

https://cdn.discordapp.com/attachments/1220364740820336661/1221916468569047050/image.png?ex=66145164&is=6601dc64&hm=2cba1c01f15ae3bd676a2993f8843eaef572e3e16510d832c4c741c83a8efa5d&

**Comment by burkejasonj** [comment]
Fixed in 0.3.1.
