### ISSUE TITLE
Chiseled Bookshelf textures not loading

### ISSUE THREAD

**Issue by Jera1dl** [burkejasonj/Mystic-SMP#2]
After making a chiseled bookshelf and placing it, the textures don't show up.

![2024-04-02_18 36 19](https://github.com/burkejasonj/Mystic-SMP/assets/164943084/a3a455f0-a3f4-449f-90ab-7bd3ac8ddcb8)

**Comment by burkejasonj** [comment]
Issue is with Ultimacraft Models, investigating issue. Targeting 0.4.2

**Comment by burkejasonj** [comment]
Removing Ultimacraft Models in 0.4.2, pending resource pack update.
